
"""게임에서 여러 모듈이 공유하는 변경 가능한 기본 설정."""

# 네트워크
SERVER_IP = "127.0.0.1"
SERVER_PORT = 5555
NETWORK_BUFFER_SIZE = 4096
SERVER_SEED = 12345

# 화면과 게임 루프
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
FPS = 64

# 플레이어
PLAYER_MAX_HP = 100
PLAYER_NORMAL_SPEED = 5
PLAYER_SPRINT_SPEED = 8
PLAYER_HASTE_SPEED = 10
PLAYER_DASH_SPEED = 15
PLAYER_DASH_DURATION_MS = 200
PLAYER_DASH_COOLDOWN_MS = 1500
DEFAULT_WEAPON_ID = "pistol"
DEFAULT_BULLET_SIZE = 1
DEFAULT_BULLET_DAMAGE = 10
BULLET_IMAGE_FILE = "sprite_0017.png"

# 맵과 스폰
MAP_WIDTH_TILES = 200
MAP_HEIGHT_TILES = 200
SPAWN_MIN_X = 40
SPAWN_MAX_X = 160
SPAWN_MIN_Y = 40
SPAWN_MAX_Y = 160
MAP_HOUSE_COUNT = 48
MAP_HOUSE_MARGIN = 32
MAP_HOUSE_MIN_SIZE = 12
MAP_HOUSE_MAX_SIZE = 20
MAP_SAFE_ZONE_MIN = 72
MAP_SAFE_ZONE_MAX = 112
MAP_TREASURE_CHANCE = 0.65
MAP_HOUSE_PADDING = 4

# 카메라
CAMERA_FOV = 1.0
CAMERA_FOV_MAX = 1.35
SPRINT_CAMERA_FOV = 1.22
CAMERA_FOV_SMOOTH = 0.12

# 전투와 스킬
MELEE_RANGE = 150
BULLET_TARGET_DISTANCE = 1000
BOMB_DELAY_MS = 600
BOMB_RADIUS = 120
BOMB_DAMAGE = 30
BOMB_INSTALL_EFFECT_MS = 600
HASTE_DURATION_MS = 5000
VISION_DURATION_MS = 3000
SHIELD_DURATION_MS = 5000
STEALTH_DURATION_MS = 1500
STEALTH_COOLDOWN_MS = 10000
SUPPLY_DROP_INTERVAL_MS = 18000
SUPPLY_DROP_CHANCE = 0.35
SUPPLY_DROP_MAX = 3
SUPPLY_HEAL_AMOUNT = 25
SUPPLY_BUFF_DURATION_MS = 5000
SUPPLY_DROP_RADIUS = 18
SUPPLY_DROP_LIFETIME_MS = 30000
SUPPLY_REWARD_TYPES = ("heal", "haste", "shield", "skill")
CHEST_HEAL_CHANCE = 0.4
CHEST_BUFF_CHANCE = 0.3
INVENTORY_SIZE = (720, 210)
INVENTORY_X = (SCREEN_WIDTH - INVENTORY_SIZE[0]) // 2
INVENTORY_Y = 390
INVENTORY_ITEM_COLUMNS = 6
INVENTORY_ITEM_ALPHA = 75
EXPLOSION_DURATION_MS = 350
SKILL_COOLDOWN_MS = 5000
SCREEN_SHAKE_MAX = 12
MELEE_SHAKE = 3
SHIELD_ALPHA = 150
HEALTH_GREEN_THRESHOLD = 0.8
HEALTH_YELLOW_THRESHOLD = 0.4
HEAD_HITBOX_WIDTH_RATIO = 0.55
HEAD_HITBOX_HEIGHT_RATIO = 0.35
BODY_HITBOX_INSET_RATIO = 0.08
HEADSHOT_DAMAGE_MULTIPLIER = 2

# UI
HP_FRAME_SIZE = (360, 120)
VISION_OVERLAY_ALPHA = 170
SKILL_ICON_SIZE = 70
QUICK_SLOT_SIZE = 80
SKILL_PANEL_SIZE = (720, 180)
SKILL_PANEL_X = (SCREEN_WIDTH - SKILL_PANEL_SIZE[0]) // 2
SKILL_PANEL_Y = SCREEN_HEIGHT - SKILL_PANEL_SIZE[1] - 30
QUICK_SLOT_START_X = (SCREEN_WIDTH - QUICK_SLOT_SIZE * 3 - 40) // 2
QUICK_SLOT_Y = SCREEN_HEIGHT - QUICK_SLOT_SIZE - 80

# 기존 코드와의 호환 별칭
ServerIp = SERVER_IP
ServerPort = SERVER_PORT
ScreenX = SCREEN_WIDTH
ScreenY = SCREEN_HEIGHT
PlayerSpd = PLAYER_NORMAL_SPEED
Bullet_Size = 30



